#!/usr/bin/env bash
# One-time setup so the convsearch Chrome extension can auto-start the local server
# via Chrome Native Messaging (macOS / Linux).
#
# After loading the unpacked extension in chrome://extensions, copy its ID and run:
#   bash scripts/install-native-host.sh <EXTENSION_ID> [WORKSPACE] [PORT]
#
# This script:
#   1. Resolves how to run convsearch (uv-managed project, or a bare `convsearch`).
#   2. Writes scripts/native-host/host-config.json.
#   3. Generates scripts/native-host/convsearch-host.sh (the launcher Chrome runs).
#   4. Renders scripts/native-host/com.convsearch.host.json from the template.
#   5. Copies the manifest into Chrome's per-user NativeMessagingHosts directory.
#
# It is idempotent: re-running overwrites the generated files and manifest.

set -euo pipefail

EXTENSION_ID="${1:-}"
if [ -z "$EXTENSION_ID" ]; then
  echo "usage: bash scripts/install-native-host.sh <EXTENSION_ID> [WORKSPACE] [PORT]" >&2
  exit 1
fi

# Resolve paths relative to this script so it can be run from anywhere.
SCRIPT_SOURCE="${BASH_SOURCE[0]}"
SCRIPTS_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"
REPO_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"
HOST_DIR="$SCRIPTS_DIR/native-host"
NATIVE_HOST_PY="$SCRIPTS_DIR/native_host.py"

WORKSPACE_INPUT="${2:-$REPO_ROOT/workspace}"
PORT="${3:-8756}"

mkdir -p "$HOST_DIR"
if [ ! -f "$NATIVE_HOST_PY" ]; then
  echo "error: native_host.py not found at $NATIVE_HOST_PY" >&2
  exit 1
fi

# Absolute workspace path (need not exist yet).
mkdir -p "$(dirname "$WORKSPACE_INPUT")" 2>/dev/null || true
if command -v python3 >/dev/null 2>&1; then
  WORKSPACE_ABS="$(python3 -c 'import os,sys; print(os.path.abspath(sys.argv[1]))' "$WORKSPACE_INPUT")"
else
  case "$WORKSPACE_INPUT" in
    /*) WORKSPACE_ABS="$WORKSPACE_INPUT" ;;
    *)  WORKSPACE_ABS="$(pwd)/$WORKSPACE_INPUT" ;;
  esac
fi

LOG_DIR="$REPO_ROOT/tmp"
mkdir -p "$LOG_DIR"
LOG_PATH="$LOG_DIR/native-host.log"

# --------------------------------------------------------------------------- #
# resolve how to run convsearch (server) and python (host)                    #
# --------------------------------------------------------------------------- #

has_uv=0;   command -v uv >/dev/null 2>&1 && has_uv=1
has_cs=0;   command -v convsearch >/dev/null 2>&1 && has_cs=1
has_proj=0; { [ -f "$REPO_ROOT/pyproject.toml" ] || [ -d "$REPO_ROOT/.venv" ]; } && has_proj=1

if [ "$has_uv" = 1 ] && [ "$has_proj" = 1 ]; then
  SERVER_COMMAND_JSON='["uv","run","--no-sync","convsearch"]'
  INTERPRETER='uv run --no-sync python'
elif [ "$has_cs" = 1 ]; then
  SERVER_COMMAND_JSON='["convsearch"]'
  if command -v python3 >/dev/null 2>&1; then
    INTERPRETER='python3'
  elif command -v python >/dev/null 2>&1; then
    INTERPRETER='python'
  else
    echo "error: convsearch is on PATH but no python interpreter was found for the native host." >&2
    exit 1
  fi
elif [ "$has_uv" = 1 ]; then
  SERVER_COMMAND_JSON='["uv","run","--no-sync","convsearch"]'
  INTERPRETER='uv run --no-sync python'
else
  echo "error: neither 'uv' nor 'convsearch' is available on PATH." >&2
  echo "Install the engine first: uv sync --extra ml --extra llm" >&2
  exit 1
fi

# --------------------------------------------------------------------------- #
# JSON escaping helper (for paths that may contain backslashes/quotes)        #
# --------------------------------------------------------------------------- #
json_escape() {
  # Escape backslash and double-quote for embedding in a JSON string.
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# --------------------------------------------------------------------------- #
# 1) host-config.json                                                          #
# --------------------------------------------------------------------------- #
CONFIG_PATH="$HOST_DIR/host-config.json"
cat > "$CONFIG_PATH" <<EOF
{
  "command": $SERVER_COMMAND_JSON,
  "workspace": "$(json_escape "$WORKSPACE_ABS")",
  "port": $PORT,
  "log": "$(json_escape "$LOG_PATH")"
}
EOF
echo "Wrote host config:   $CONFIG_PATH"

# --------------------------------------------------------------------------- #
# 2) convsearch-host.sh launcher                                              #
# --------------------------------------------------------------------------- #
LAUNCHER_PATH="$HOST_DIR/convsearch-host.sh"
cat > "$LAUNCHER_PATH" <<EOF
#!/usr/bin/env bash
# Generated by install-native-host.sh - do not edit by hand.
# cd to the repo root so \`uv run\` (and relative resolution) works regardless of the
# working directory Chrome hands the launcher.
cd "$REPO_ROOT" || exit 1
exec $INTERPRETER "$NATIVE_HOST_PY" "\$@"
EOF
chmod +x "$LAUNCHER_PATH"
echo "Wrote launcher:      $LAUNCHER_PATH"

# --------------------------------------------------------------------------- #
# 3) render com.convsearch.host.json                                          #
# --------------------------------------------------------------------------- #
TEMPLATE_PATH="$HOST_DIR/com.convsearch.host.json.template"
MANIFEST_PATH="$HOST_DIR/com.convsearch.host.json"
if [ ! -f "$TEMPLATE_PATH" ]; then
  echo "error: manifest template not found at $TEMPLATE_PATH" >&2
  exit 1
fi
HOST_PATH_ESC="$(json_escape "$LAUNCHER_PATH")"
sed -e "s|__HOST_PATH__|$HOST_PATH_ESC|g" \
    -e "s|__EXTENSION_ID__|$EXTENSION_ID|g" \
    "$TEMPLATE_PATH" > "$MANIFEST_PATH"
echo "Wrote host manifest: $MANIFEST_PATH"

# --------------------------------------------------------------------------- #
# 4) copy the manifest into Chrome's NativeMessagingHosts directory           #
# --------------------------------------------------------------------------- #
install_manifest() {
  local dir="$1" name="$2"
  mkdir -p "$dir"
  cp "$MANIFEST_PATH" "$dir/com.convsearch.host.json"
  echo "Installed for $name: $dir/com.convsearch.host.json"
}

case "$(uname -s)" in
  Darwin)
    install_manifest "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts" "Chrome"
    install_manifest "$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts" "Edge" 2>/dev/null || true
    ;;
  *)
    install_manifest "$HOME/.config/google-chrome/NativeMessagingHosts" "Chrome"
    install_manifest "$HOME/.config/microsoft-edge/NativeMessagingHosts" "Edge" 2>/dev/null || true
    install_manifest "$HOME/.config/chromium/NativeMessagingHosts" "Chromium" 2>/dev/null || true
    ;;
esac

echo ""
echo "Native messaging host installed."
echo "  Extension id: $EXTENSION_ID"
echo "  Workspace:    $WORKSPACE_ABS"
echo "  Port:         $PORT"
echo "  Log:          $LOG_PATH"
echo ""
echo "Next: reload the extension in chrome://extensions (or restart the browser),"
echo "then the extension will auto-start the server whenever it is offline."
echo ""
echo "Note: convsearch must be installed (uv sync) and, for a fresh workspace, the"
echo "history must be imported and indexed first, or the server will serve empty results."
